readme.md: Fix syntax error in the example
Fix the following error in the example provide in section Usage:

let rpi = require('raspi-ver);
                  ^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token

Signed-off-by: Leon Anavi <leon@anavi.org>